services:
  backend-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - db-service

  db-service:
    image: postgres:18
    restart: unless-stopped
    shm_size: 128mb
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - db-service
