services:
  backend-service:
    image: pe_bootcamp/backend:1.0.0
    container_name: backend
    ports:
      - 5000:5000
    # volumes:
    #   - .:/usr/src/app  # For development
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PWD}@postgres_db/${POSTGRES_DB}
    depends_on:
      db-service:
        condition: service_healthy

  db-service:
    image: postgres:18
    restart: unless-stopped
    shm_size: 128mb
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db-service

volumes:
  postgres_data:
